### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by bmvaghera** [Senitopeng/fbbrute#3]
File "MBF2.pye", line 1, in <module>
  File "<script>", line 12, in <module>
  File "<script>", line 12, in <module>
  File "<script>", line 407, in <module>
  File "<script>", line 400, in menu
  File "<script>", line 339, in idteman
NameError: global name 'id_teman' is not defined

**Comment by hilmi7** [comment]
what this is

**Comment by Senitopeng** [comment]
Repo I close

Pada tanggal Sel, 1 Jan 2019 23.34 hilmi7 <notifications@github.com menulis:

**Comment by hilmi7** [comment]
Cara ngejalani fbhack version 2 gmna ?

**Comment by Senitopeng** [comment]
Isi file di Reponya sudah ku hapus

Pada Rabu, 02 Januari 2019, hilmi7 <notifications@github.com> menulis:

**Comment by hilmi7** [comment]
buat lagi lah gan , sekalian cara ngehack wa

Pada tanggal Rab, 2 Jan 2019 12.44 Senitopeng <notifications@github.com
menulis:

**Comment by Senitopeng** [comment]
Ga.. Ku Dah vakum

Pada Rabu, 02 Januari 2019, hilmi7 <notifications@github.com> menulis:

**Comment by hilmi7** [comment]
Bang bisa buat cheat berlian hago gak ? , kalo bisa nanti saya bayarin
cheat nya

Pada tanggal Rab, 2 Jan 2019 19.22, Senitopeng <notifications@github.com>
menulis:

**Comment by raija-12** [comment]
<notifications@github.com
